### ISSUE TITLE
Epic React

### ISSUE THREAD

**Issue by dschapman** [dschapman/dschapman#2]
### Progress

- [x] React Fundamentals
- [x] React Hooks
- [ ] Advanced React Hooks
- [ ] Advanced React Patterns
- [ ] React Performance
- [ ] Testing React Apps
- [ ] React Suspense
- [ ] Build an Epic React App

**Comment by dschapman** [comment]
[Daniel Chapman-react-fundamentals-certificate.pdf](https://github.com/dschapman/dschapman/files/5319112/Daniel.Chapman-epic-react-certificate.1.pdf)

**Comment by dschapman** [comment]
[Daniel Chapman-react-hooks-certificate.pdf](https://github.com/dschapman/dschapman/files/5388653/Daniel.Chapman-react-hooks-certificate.pdf)
